# Generated by Django 3.0.3 on 2020-02-20 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_friendlist_mail_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_qq',
        ),
    ]
