# Generated by Django 3.0.3 on 2020-02-21 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_user_user_qq'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mail',
            old_name='_from',
            new_name='receiver',
        ),
        migrations.RenameField(
            model_name='mail',
            old_name='sendto',
            new_name='sender',
        ),
        migrations.RemoveField(
            model_name='mail',
            name='user_email',
        ),
        migrations.AddField(
            model_name='mail',
            name='status',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
