# Generated by Django 3.0.3 on 2020-02-21 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200221_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
