# Generated by Django 3.0.3 on 2020-02-21 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200221_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_head',
            field=models.ImageField(default='\x07pp\\static\\head\\defaulthead.jpg', upload_to='head'),
        ),
    ]
