# Generated by Django 3.0.3 on 2020-02-21 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200221_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_head',
            field=models.ImageField(default='head/defaulthead.jpg', upload_to='head'),
        ),
    ]
