# Generated by Django 3.0.3 on 2020-02-21 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200221_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='logon_time',
            field=models.DateField(auto_now_add=True),
        ),
    ]
