# Generated by Django 3.0.3 on 2020-02-23 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20200222_0116'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='files',
            field=models.FileField(null=True, upload_to='upload'),
        ),
    ]
