# Generated by Django 3.0.3 on 2020-02-26 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_mail_files'),
    ]

    operations = [
        migrations.CreateModel(
            name='attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='upload')),
            ],
            options={
                'db_table': 'attachment',
            },
        ),
        migrations.RemoveField(
            model_name='mail',
            name='files',
        ),
        migrations.AddField(
            model_name='mail',
            name='files',
            field=models.ManyToManyField(related_name='files', to='app.attachment'),
        ),
    ]
