# Generated by Django 3.0.3 on 2020-02-29 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20200227_0044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mymail',
            old_name='status',
            new_name='sendstatus',
        ),
        migrations.AddField(
            model_name='mymail',
            name='readstatus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mymail',
            name='uuid',
            field=models.CharField(default='', max_length=32),
        ),
    ]
