# Generated by Django 3.0.3 on 2020-03-01 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20200301_0257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mymail',
            old_name='uuid',
            new_name='mid',
        ),
    ]
